apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendcal
  labels: 
    app: backend
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
        containers:
        - name: backendcal
          image: cabunga/backcal