apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendcal
  labels: 
    app: frontend
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
        containers:
        - name: frontendcal
          image: cabunga/frontcal:nginx