apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
 name: calingres
 annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: calculadora.info
    http:
       paths:
        - path: /
          backend:
            serviceName: frontcal
            servicePort: 80
        - path: /api
          backend:
             serviceName: backcal
             servicePort: 8080
